mixed-port: 7890
allow-lan: false
mode: rule
unified-delay: true
tcp-concurrent: true
geodata-mode: true
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
log-level: info
dns:
  enable: false
  ipv6: false
  default-nameserver: [223.5.5.5, 119.29.29.29]
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver: ['114.114.114.114', '223.5.5.5', 'https://dns.alidns.com/dns-query']
proxies:
  # æ·»åŠ  DIRECT ä»£ç†ï¼Œç”¨äºâ€œä¸ç”¨ä»£ç†â€é€‰é¡¹
  - { name: ğŸ¯ ä¸ç”¨ä»£ç†, type: direct }
  - { name: æ— é™æµé‡ã€ä¸ä¿è¯å¯ç”¨ã€‘æ—¥æœ¬-ä»˜è´¹, server: jp0731.aihost.top, port: 443, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: true, network: ws, ws-opts: { path: /macos, headers: { Host: jp0731.aihost.top }, v2ray-http-upgrade: true } }
  - { name: æ—¥æœ¬1a-ä»˜è´¹èŠ‚ç‚¹, server: jpas.showmyip.top, port: 11708, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false, network: ws, ws-opts: { path: /jp-speedtest, headers: { Host: jpas.showmyip.top } } }
  - { name: æ—¥æœ¬1c-ä»˜è´¹èŠ‚ç‚¹, server: jpc.showmyip.top, port: 11708, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false, network: ws, ws-opts: { path: /jp-speedtest, headers: { Host: jpc.showmyip.top } } }
  - { name: æ—¥æœ¬2a-ä»˜è´¹èŠ‚ç‚¹, server: jpas.showmyip.top, port: 11343, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: æ—¥æœ¬2c-ä»˜è´¹èŠ‚ç‚¹, server: jpc.showmyip.top, port: 11343, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: æ—¥æœ¬3b-ä»˜è´¹èŠ‚ç‚¹, server: jpbm.showmyip.top, port: 11821, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: æ—¥æœ¬3c-ä»˜è´¹èŠ‚ç‚¹, server: jpc.showmyip.top, port: 11821, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: æ—¥æœ¬4b-ä»˜è´¹èŠ‚ç‚¹, server: jpbm.showmyip.top, port: 11701, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: æ—¥æœ¬4c-ä»˜è´¹èŠ‚ç‚¹, server: jpc.showmyip.top, port: 11701, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe056773335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: æ—¥æœ¬5a-ä»˜è´¹èŠ‚ç‚¹, server: jpas.showmyip.top, port: 11702, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: æ—¥æœ¬5b-ä»˜è´¹èŠ‚ç‚¹, server: jpbm.showmyip.top, port: 11702, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: æ—¥æœ¬6a-ä»˜è´¹èŠ‚ç‚¹, server: jpas.showmyip.top, port: 11703, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: æ—¥æœ¬6b-ä»˜è´¹èŠ‚ç‚¹, server: jpbm.showmyip.top, port: 11703, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: éŸ©å›½a-ä»˜è´¹èŠ‚ç‚¹, server: kr1a.showmyip.top, port: 11700, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: éŸ©å›½b-ä»˜è´¹èŠ‚ç‚¹, server: kr1b.showmyip.top, port: 11700, type: vmess, uuid: a06fe9b7-c4eb-39cc-9f25-f9fe05677335, alterId: 0, cipher: auto, udp: true, tls: false }
  - { name: 5å€ç‡|æ¸¸æˆ|æ—¥æœ¬1-ä»˜è´¹èŠ‚ç‚¹, server: gamejp.showmyip.top, port: '11853', type: ss, cipher: aes-256-gcm, password: KsQnMI, udp: true }
  - { name: 5å€ç‡|æ¸¸æˆ|éŸ©å›½-ä»˜è´¹èŠ‚ç‚¹, server: gamekr.showmyip.top, port: '11347', type: ss, cipher: aes-256-gcm, password: KsQnMI, udp: true }

proxy-groups:
  - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ ä¸ç”¨ä»£ç† # å¼•ç”¨å·²å®šä¹‰çš„ DIRECT ä»£ç†
      - æ— é™æµé‡ã€ä¸ä¿è¯å¯ç”¨ã€‘æ—¥æœ¬-ä»˜è´¹
      - æ—¥æœ¬1a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬1c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬2a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬2c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬3b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬3c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬4b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬4c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬5a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬5b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬6a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬6b-ä»˜è´¹èŠ‚ç‚¹
      - éŸ©å›½a-ä»˜è´¹èŠ‚ç‚¹
      - éŸ©å›½b-ä»˜è´¹èŠ‚ç‚¹
      - 5å€ç‡|æ¸¸æˆ|æ—¥æœ¬1-ä»˜è´¹èŠ‚ç‚¹
      - 5å€ç‡|æ¸¸æˆ|éŸ©å›½-ä»˜è´¹èŠ‚ç‚¹

  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://cp.cloudflare.com
    interval: 86400
    proxies:
      - æ— é™æµé‡ã€ä¸ä¿è¯å¯ç”¨ã€‘æ—¥æœ¬-ä»˜è´¹
      - æ—¥æœ¬1a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬1c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬2a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬2c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬3b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬3c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬4b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬4c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬5a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬5b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬6a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬6b-ä»˜è´¹èŠ‚ç‚¹
      - éŸ©å›½a-ä»˜è´¹èŠ‚ç‚¹
      - éŸ©å›½b-ä»˜è´¹èŠ‚ç‚¹
      - 5å€ç‡|æ¸¸æˆ|æ—¥æœ¬1-ä»˜è´¹èŠ‚ç‚¹
      - 5å€ç‡|æ¸¸æˆ|éŸ©å›½-ä»˜è´¹èŠ‚ç‚¹

  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ ä¸ç”¨ä»£ç† # å¼•ç”¨å·²å®šä¹‰çš„ DIRECT ä»£ç†
      - æ— é™æµé‡ã€ä¸ä¿è¯å¯ç”¨ã€‘æ—¥æœ¬-ä»˜è´¹
      - æ—¥æœ¬1a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬1c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬2a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬2c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬3b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬3c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬4b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬4c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬5a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬5b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬6a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬6b-ä»˜è´¹èŠ‚ç‚¹
      - éŸ©å›½a-ä»˜è´¹èŠ‚ç‚¹
      - éŸ©å›½b-ä»˜è´¹èŠ‚ç‚¹
      - 5å€ç‡|æ¸¸æˆ|æ—¥æœ¬1-ä»˜è´¹èŠ‚ç‚¹
      - 5å€ç‡|æ¸¸æˆ|éŸ©å›½-ä»˜è´¹èŠ‚ç‚¹

  - name: ğŸ§± å›½å†…åª’ä½“
    type: select
    proxies:
      - ğŸ¯ ä¸ç”¨ä»£ç† # å¼•ç”¨å·²å®šä¹‰çš„ DIRECT ä»£ç†
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - æ— é™æµé‡ã€ä¸ä¿è¯å¯ç”¨ã€‘æ—¥æœ¬-ä»˜è´¹
      - æ—¥æœ¬1a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬1c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬2a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬2c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬3b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬3c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬4b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬4c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬5a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬5b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬6a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬6b-ä»˜è´¹èŠ‚ç‚¹
      - éŸ©å›½a-ä»˜è´¹èŠ‚ç‚¹
      - éŸ©å›½b-ä»˜è´¹èŠ‚ç‚¹
      - 5å€ç‡|æ¸¸æˆ|æ—¥æœ¬1-ä»˜è´¹èŠ‚ç‚¹
      - 5å€ç‡|æ¸¸æˆ|éŸ©å›½-ä»˜è´¹èŠ‚ç‚¹

  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - ğŸ¯ ä¸ç”¨ä»£ç† # å¼•ç”¨å·²å®šä¹‰çš„ DIRECT ä»£ç†
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - æ— é™æµé‡ã€ä¸ä¿è¯å¯ç”¨ã€‘æ—¥æœ¬-ä»˜è´¹
      - æ—¥æœ¬1a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬1c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬2a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬2c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬3b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬3c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬4b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬4c-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬5a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬5b-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬6a-ä»˜è´¹èŠ‚ç‚¹
      - æ—¥æœ¬6b-ä»˜è´¹èŠ‚ç‚¹
      - éŸ©å›½a-ä»˜è´¹èŠ‚ç‚¹
      - éŸ©å›½b-ä»˜è´¹èŠ‚ç‚¹
      - 5å€ç‡|æ¸¸æˆ|æ—¥æœ¬1-ä»˜è´¹èŠ‚ç‚¹
      - 5å€ç‡|æ¸¸æˆ|éŸ©å›½-ä»˜è´¹èŠ‚ç‚¹

rules:
  # æœ¬åœ°ç½‘ç»œç›´è¿ï¼Œé¿å…ä»£ç†å†…éƒ¨æµé‡
  - IP-CIDR,127.0.0.1/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT

  # GeoIP CN ç›´è¿ (å¦‚æœgeodata-mode: trueï¼Œæ­¤è§„åˆ™å°†æ ¹æ®IPåœ°å€åˆ¤æ–­ä¸ºä¸­å›½å¤§é™†IPç›´è¿)
  # éœ€è¦ç¡®ä¿ geox-url ä¸­çš„ geoip.dat å’Œ geosite.dat å¯ä»¥æ­£å¸¸ä¸‹è½½
  - GEOIP,CN,DIRECT,no-resolve

  # å¸¸è§çš„å›½å¤–åª’ä½“å’ŒæœåŠ¡é€šè¿‡ä»£ç†
  - DOMAIN-SUFFIX,googleapis.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,youtube.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,youtu.be,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,npmjs.org,ğŸŒ å›½å¤–åª’ä½“ # å¤„ç† npmjs.org çš„æµé‡
  - DOMAIN-SUFFIX,google.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,google.com.hk,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,gmail.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,twitter.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,facebook.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,instagram.com,ğŸŒ å›½å¤–åª’ä½“

  # æœ€ç»ˆè§„åˆ™ï¼Œæ‰€æœ‰æœªåŒ¹é…çš„æµé‡éƒ½é€šè¿‡èŠ‚ç‚¹é€‰æ‹©
  - MATCH,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
